import { TutorialFlow } from '../../types/tutorial';

export const onboardingFlow: TutorialFlow = {
  id: 'neural-flow-onboarding',
  name: 'Neural Flow Onboarding',
  description: 'Get started with Neural Flow and learn the basics of AI-powered productivity',
  category: 'onboarding',
  difficulty: 'beginner',
  estimatedDuration: 10,
  steps: [
    {
      id: 'welcome',
      title: 'Welcome to Neural Flow',
      content: 'Welcome to Neural Flow! This AI-powered workspace learns from your behavior to optimize your productivity. Let\'s start with a quick tour.',
      target: 'body',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
    {
      id: 'navigation',
      title: 'Navigation Basics',
      content: 'This is your main navigation. You can access different features like Workspace, Analytics, and Collaboration from here.',
      target: '[data-tutorial="main-nav"]',
      position: 'bottom',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'workspace',
      title: 'Your Adaptive Workspace',
      content: 'Your workspace automatically adapts to your work patterns. Tasks, projects, and tools are organized based on your behavior.',
      target: '[data-tutorial="workspace"]',
      position: 'right',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'ai-assistant',
      title: 'AI Assistant',
      content: 'Your AI assistant provides contextual help and suggestions. Click here to see what it can do for you.',
      target: '[data-tutorial="ai-assistant"]',
      position: 'left',
      action: 'click',
      nextTrigger: 'action',
      skippable: true,
    },
    {
      id: 'task-creation',
      title: 'Create Your First Task',
      content: 'Let\'s create your first task. Click the "Add Task" button to get started. This will help you organize your work effectively.',
      target: '[data-tutorial="add-task"], [data-tutorial="quick-add-sidebar"]',
      position: 'top',
      action: 'click',
      nextTrigger: 'action',
      skippable: false,
      required: true,
      fallbackTargets: ['[data-tutorial="quick-add-sidebar"]'],
      beforeShow: () => {
        // Ensure we're in the tasks view
        const currentUrl = window.location.href;
        if (!currentUrl.includes('tutorial=true')) {
          window.history.replaceState({}, '', window.location.pathname + '?tutorial=true');
        }
      },
    },
    {
      id: 'task-input',
      title: 'Task Details',
      content: 'Enter a task title and description. The AI will automatically suggest priority and estimated time.',
      target: '[data-tutorial="task-input"]',
      position: 'right',
      action: 'input',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'completion',
      title: 'You\'re All Set!',
      content: 'Congratulations! You\'ve completed the onboarding. Neural Flow will now start learning from your behavior to optimize your workflow.',
      target: 'body',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
  ],
  rewards: [
    {
      type: 'badge',
      id: 'onboarding-complete',
      name: 'Getting Started',
      description: 'Completed the Neural Flow onboarding',
      icon: 'rocket',
    },
    {
      type: 'feature_unlock',
      id: 'advanced-features',
      name: 'Advanced Features',
      description: 'Unlocked access to advanced AI features',
      unlocks: ['ai-content-generation', 'predictive-scheduling'],
    },
  ],
};

export const workspaceFlow: TutorialFlow = {
  id: 'workspace-mastery',
  name: 'Workspace Mastery',
  description: 'Master the adaptive workspace and learn how to leverage AI for maximum productivity',
  category: 'feature',
  difficulty: 'intermediate',
  estimatedDuration: 15,
  prerequisites: ['neural-flow-onboarding'],
  steps: [
    {
      id: 'workspace-overview',
      title: 'Workspace Intelligence',
      content: 'Your workspace uses AI to predict what you need next. Let\'s explore how it adapts to your work patterns.',
      target: '[data-tutorial="workspace-main"]',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
    {
      id: 'context-toolbar',
      title: 'Context-Aware Toolbar',
      content: 'This toolbar changes based on your current task and context. Notice how it shows relevant tools and shortcuts.',
      target: '[data-tutorial="context-toolbar"]',
      position: 'bottom',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'predictive-suggestions',
      title: 'Predictive Suggestions',
      content: 'The AI suggests your next tasks based on patterns. These suggestions get more accurate over time.',
      target: '[data-tutorial="task-suggestions"]',
      position: 'left',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'drag-drop',
      title: 'Drag & Drop Organization',
      content: 'Try dragging a task to a different column. The AI learns from your organization preferences.',
      target: '[data-tutorial="task-board"]',
      position: 'top',
      action: 'hover',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'quick-actions',
      title: 'Quick Actions',
      content: 'Right-click on any task to see context-specific quick actions. These are personalized based on your workflow.',
      target: '[data-tutorial="task-card"]',
      position: 'right',
      nextTrigger: 'manual',
      skippable: true,
    },
  ],
  rewards: [
    {
      type: 'badge',
      id: 'workspace-master',
      name: 'Workspace Master',
      description: 'Mastered the adaptive workspace features',
      icon: '🏆',
    },
    {
      type: 'customization',
      id: 'custom-layouts',
      name: 'Custom Layouts',
      description: 'Unlocked ability to create custom workspace layouts',
    },
  ],
};

export const aiContentFlow: TutorialFlow = {
  id: 'ai-content-generation',
  name: 'AI Content Generation',
  description: 'Learn how to use AI to generate, enhance, and optimize your content',
  category: 'feature',
  difficulty: 'intermediate',
  estimatedDuration: 12,
  prerequisites: ['neural-flow-onboarding'],
  steps: [
    {
      id: 'content-intro',
      title: 'AI-Powered Content',
      content: 'Neural Flow can help you create, enhance, and optimize content using advanced AI models.',
      target: '[data-tutorial="content-panel"]',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
    {
      id: 'content-generation',
      title: 'Generate Content',
      content: 'Click here to open the content generation panel. You can create documents, emails, and more.',
      target: '[data-tutorial="generate-content"]',
      position: 'bottom',
      action: 'click',
      nextTrigger: 'action',
      skippable: true,
    },
    {
      id: 'style-analysis',
      title: 'Style Learning',
      content: 'The AI learns your writing style from your existing content to match your voice.',
      target: '[data-tutorial="style-settings"]',
      position: 'right',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'content-enhancement',
      title: 'Content Enhancement',
      content: 'Select any text to see AI-powered enhancement suggestions like grammar, tone, and clarity improvements.',
      target: '[data-tutorial="content-editor"]',
      position: 'top',
      nextTrigger: 'manual',
      skippable: true,
    },
  ],
  rewards: [
    {
      type: 'feature_unlock',
      id: 'advanced-ai',
      name: 'Advanced AI Models',
      description: 'Unlocked access to advanced AI content models',
      unlocks: ['gpt-4-integration', 'custom-prompts'],
    },
  ],
};

export const collaborationFlow: TutorialFlow = {
  id: 'collaboration-features',
  name: 'Smart Collaboration',
  description: 'Discover how AI enhances team collaboration and communication',
  category: 'feature',
  difficulty: 'intermediate',
  estimatedDuration: 8,
  prerequisites: ['workspace-mastery'],
  steps: [
    {
      id: 'collab-intro',
      title: 'Intelligent Collaboration',
      content: 'Neural Flow uses AI to optimize team collaboration by understanding team dynamics and expertise.',
      target: '[data-tutorial="collaboration-panel"]',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
    {
      id: 'expertise-matching',
      title: 'Expertise Matching',
      content: 'When you need help, the AI suggests the best team member to contact based on their expertise.',
      target: '[data-tutorial="expert-suggestions"]',
      position: 'left',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'real-time-collab',
      title: 'Real-time Collaboration',
      content: 'Multiple team members can work on the same project simultaneously with intelligent conflict resolution.',
      target: '[data-tutorial="real-time-editor"]',
      position: 'top',
      nextTrigger: 'manual',
      skippable: true,
    },
  ],
  rewards: [
    {
      type: 'badge',
      id: 'collaboration-expert',
      name: 'Collaboration Expert',
      description: 'Mastered AI-powered collaboration features',
      icon: 'handshake',
    },
  ],
};

export const advancedFlow: TutorialFlow = {
  id: 'advanced-ai-features',
  name: 'Advanced AI Features',
  description: 'Explore cutting-edge AI capabilities for power users',
  category: 'advanced',
  difficulty: 'advanced',
  estimatedDuration: 20,
  prerequisites: ['workspace-mastery', 'ai-content-generation'],
  steps: [
    {
      id: 'advanced-intro',
      title: 'Advanced AI Capabilities',
      content: 'You\'re ready for the most powerful AI features in Neural Flow. These tools can dramatically enhance your productivity.',
      target: 'body',
      position: 'center',
      nextTrigger: 'manual',
      skippable: false,
    },
    {
      id: 'predictive-analytics',
      title: 'Predictive Analytics',
      content: 'View detailed analytics about your productivity patterns and AI-powered forecasts.',
      target: '[data-tutorial="analytics-dashboard"]',
      position: 'right',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'custom-models',
      title: 'Custom AI Models',
      content: 'Train custom AI models on your specific workflow and data for personalized automation.',
      target: '[data-tutorial="model-training"]',
      position: 'bottom',
      nextTrigger: 'manual',
      skippable: true,
    },
    {
      id: 'automation-rules',
      title: 'Intelligent Automation',
      content: 'Set up complex automation rules that adapt based on context and learning.',
      target: '[data-tutorial="automation-panel"]',
      position: 'left',
      nextTrigger: 'manual',
      skippable: true,
    },
  ],
  rewards: [
    {
      type: 'achievement',
      id: 'ai-master',
      name: 'AI Master',
      description: 'Achieved mastery of all Neural Flow AI features',
      icon: 'brain',
    },
    {
      type: 'feature_unlock',
      id: 'beta-features',
      name: 'Beta Features',
      description: 'Unlocked access to experimental AI features',
      unlocks: ['neural-search', 'predictive-ui'],
    },
  ],
};

export const defaultTutorialFlows: TutorialFlow[] = [
  onboardingFlow,
  workspaceFlow,
  aiContentFlow,
  collaborationFlow,
  advancedFlow,
];